version: '3'
services:
  app:
    build: .
    image: foxyfox/velox
    container_name: velox_container
    ports:
      - "8080:8080"
    environment:
      DB_TYPE: "${DB_TYPE}"
      DB_HOSTNAME: "${DB_HOSTNAME}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DRIVER_CLASS_NAME: "${DRIVER_CLASS_NAME}"
      HIBERNATE_DIALECT: "${HIBERNATE_DIALECT}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"

