CREATE TABLE revinfo
(
  rev BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  revtstmp BIGINT
);

CREATE TABLE user_AUD
(
  id BIGINT AUTO_INCREMENT NOT NULL,
  rev BIGINT NOT NULL,
  revtype SMALLINT,
  name VARCHAR(255),
  email VARCHAR(255),
  is_admin BOOL,
  PRIMARY KEY (id, rev),
  FOREIGN KEY (rev) REFERENCES revinfo (rev)
);